# markdown
markdown: redcarpet
redcarpet:
  extensions: ["superscript","tables","with_toc_data","strikethrough"]
highlighter: pygments

exclude:
- ".ruby-version"
- ".jekyll-metadata"
- ".gitignore"
- ".travis.yml"
- todo.txt
- resources
- Gemfile
- Gemfile.lock
- Makefile
- vendor
- README.md
- CONTRIBUTING.md
- LICENSE.md

# Site metadata
name: "Data Center Optimization Initiative (DCOI)"
description: "Data Center Optimization Initiative (DCOI)"
baseurl: https://ydave-reisys.github.io/datacenters/
# Uncomment the following line for localhost development at http://127.0.0.1:4000/datacenters/
#baseurl: /datacenters/

# GitHub information
org_name: ydave-reisys
repo_name: datacenters
branch: gh-pages

# Navigation
# List links that should appear in the site sidebar here
navigation:
- text: Home
  url: /
- text: Resources for Agencies
  submenu:
    - text: Inventory Data Submission
      url:  /datacenters/inventory-data-submission/
    - text: Strategic Plan Formulation
      url:
    - text: Ordering Shared Services
      url:  /datacenters/ordering-shared-services/
    - text: Contact Information & Community of Practice
      url:
- text: Resources for the Public
  submenu:
    - text: View PDF of Memorandum
      url: /assests/documents/DCOI_DRAFT_06 22 2016.pdf
    - text: Implementation & Progress to Date
      url:

# sass
sass:
  sass_dir: _sass
