# markdown
markdown: redcarpet
redcarpet:
  extensions: ["superscript","tables","with_toc_data","strikethrough"]
highlighter: pygments

exclude:
- ".ruby-version"
- ".jekyll-metadata"
- ".gitignore"
- ".travis.yml"
- todo.txt
- resources
- Gemfile
- Gemfile.lock
- Makefile
- vendor
- README.md
- CONTRIBUTING.md
- LICENSE.md

# Site metadata
name: "Data Center Optimization Initiative (DCOI)"
description: "Data Center Optimization Initiative (DCOI)"
baseurl: https://ydave-reisys.github.io/datacenters/
# Uncomment the following line for localhost development at http://127.0.0.1:4000/datacenters/
#baseurl: /datacenters/

# GitHub information
org_name: ydave-reisys
repo_name: datacenters
branch: gh-pages

# Navigation
# List links that should appear in the site sidebar here
navigation:
- text: Home
  url: /
- text: Policy
  url: /datacenters/policy/
- text: Leadership and Responsibilities
  url: /datacenters/responsibilities/
- text: Transition to Cloud and Data Center Shared Services
  url: /datacenters/transition/
- text: Optimization of Physical Data Centers
  url: /datacenters/optimization/
- text: Metric Target Values
  url: /datacenters/metrictarget/
- text: Reporting
  url: /datacenters/reporting/
- text: Data Center Optimization Transparency
  url: /datacenters/transparency/
- text: Community Support
  url: /datacenters/community/
- text: JSON Editor Tool
  url: /datacenters/json-editor

# sass
sass:
  sass_dir: _sass
